from image_transformer.distributions.generic_distribution import GenericDistribution
from image_transformer.distributions.normal_distribution import NormalDistribution
from image_transformer.distributions.poisson_distribution import PoissonDistribution