[tool.poetry]
name = "main"
version = "0.1.0"
description = ""
authors = ["raiden <nadirkichou@hotmail.fr>"]
readme = "README.md"
packages = [
    {include = "main", from = "src"},
    {include = "image_loader", from = "src"},
    {include = "image_processor", from = "src"}
]

[tool.poetry.dependencies]
python = "^3.12"

[tool.poetry.scripts]
main = "main.index:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
