[defaults]
size = 10
output-directory = "./"
image-processor = "hexagonal"
pixels-processor = "most-frequent"
output-builder = "cairo-svg"
verbose = true
hex-colors = ["FF0000", "FF7F00", "FFFF00", "7FFF00", "00FF00", "00FF7F", "00FFFF", "007FFF", "0000FF", "7F00FF", "FF00FF", "FF007F"]
height = 100
width = 100